image_width: 640
image_height: 480
camera_name: usb_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [881.00837,   0.     , 329.64195,
           0.     , 877.68445, 297.45127,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.033532, -0.360357, 0.022877, 0.000171, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [883.43738,   0.     , 329.42591,   0.     ,
           0.     , 869.67761, 302.32206,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
